# Simple package

name: OALT-Tech-Test
parent: default

matches:
  - trigger: ":meetingtopic"
    form: |
        {{choices}}
    form_fields:
      choices:
        type: list
        values:
          - OALT HUB
          - Hardware
          - Software
          - HIVE
          - Key Meetings
          - New & Interesting
