# Simple package

name: OALT-Tech-Test
parent: default

matches:
  - trigger: ":dlimeetcategory"
    replace: |
              OALT HUB
              >
              Hardware
              >
              Software
              >
              HIVE
              >
              Key Meetings
              >
              New & Interesting
              >
